### ISSUE TITLE
refactor(dependencies): narrower import of dependencies

### ISSUE THREAD

**Issue by UrbanoFonseca** [ydataai/ydata-quality#32]
## Description
Import only the required objects from dependencies.

```python
# avoid
import pandas as pd
# replace 
from pandas import DataFrame
```

**Comment by mhetrerajat** [comment]
Hey 👋 
I can take this one if nobody is already working on it.

**Comment by UrbanoFonseca** [comment]
Hello! Kudos on the initiative, I'm assigning the issue to you. :clap: 
Feel free to open a new branch (e.g. chore/narrow-imports) and create a PR with the changes, we will review it afterwards.
